# Kickoff default config

# Characters shown in front of the query.
prompt = '> '

# space between window border and the content in pixel
padding = 100

fonts = ['Hack']     # list of otf or ttf fonts. later elements work as fallback
font_size = 24.0

[history]
decrease_interval = 48 # interval to decrease the number of launches

[colors]
# color format: rgb or rgba, if transparency is desired
background = '#000000d8'
prompt = '#87afd7'
# For search results
text = '#ffffffff'
# For the search query
text_query = '#8fb08fff'
# For the currently selected result
text_selected = '#3ba0f3ff'

[keybindings]
# keybindings syntax: ctrl/shift/alt/logo as modifiers and a key joined by '+' signs
# A list of available keys can be found here: https://docs.rs/crate/x11-keysymdef/0.2.0/source/src/keysym.json
paste = ["ctrl+v", "ctrl+shift+v"]
execute = ["KP_Enter", "Return"]
delete = ["KP_Delete", "Delete", "BackSpace"]
delete_word = ["ctrl+KP_Delete", "ctrl+Delete", "ctrl+BackSpace"]
complete = ["Tab"]
nav_up = ["Up"]
nav_down = ["Down"]
exit = ["Escape"]
