[firefox]
# Make Ctrl+Shift+c become Ctrl+c in firefox
qwerty+control+shift.c = C-c
dvp+control+shift.i = C-c

[horizon-client|vdi-w11]
# Rebind Alt+tab to behave normally
alt.tab
altgr.space = space
