wireplumber.components = [
  {
    name = "90-exclude-monitor-sink.lua", type = script/lua
    provides = custom.exclude-monitor-sink
  }
]

wireplumber.profiles = {
  main = {
    custom.exclude-monitor-sink = required
  }
}
